### ISSUE TITLE
Modifying game files violates TOS

### ISSUE THREAD

**Issue by extesy** [Ungaminga/elder-scrolls-legends-tracker#2]
According to https://www.zenimax.com/legal_terms_us, "you may not ... modify, adapt, reverse engineer or decompile the Software". Please fix the tracker to not require patched dlls otherwise it creates a risk of getting users accounts banned.

Or at least include a warning that running this tracker is against TOS and the user should accept the risk.

**Comment by Ungaminga** [comment]
yp, i'm ashured about risks.
> Or at least include a warning that running this tracker is against TOS and the user should accept the risk.

Ok. It's right idea.
