### ISSUE TITLE
Recent Release

### ISSUE THREAD

**Issue by theswoderman** [Ungaminga/elder-scrolls-legends-tracker#3]
After this most recent version my deck lsit only shows FOTDB cards and the rest are listed as unknown and the program does not track my draws. Also not sure how to use the auto-add game statistics function.

**Comment by Ungaminga** [comment]
Please export your decks w/o running tracker, by go to deck-edit deck-save some deck. Go to your game directory, pack created directory `deck` and post here. 
Game statsitics works just as it should be. But probly there are some issue with DLL updates: my tracker checks if DLLs are original and only then you got modifided (i don't sure, i'll test and post here).
Those problems will be fixed today. TY for tracking bugs.

**Comment by theswoderman** [comment]
Thanks for the update, everything I reported earlier works great now. I've also noticed that the deck tracker doesn't track cards drawn/played from prophecy (I'm guessing because they never go to your hand)

**Comment by Ungaminga** [comment]
What kind of prophecy you are sure are bugged? I had lot of fixes that behaviour.

**Comment by theswoderman** [comment]
I haven't seen the track notice any time that a card enters the battlefield without going to your hand first (prophecy, gortwog, altar of despair, etc.)
